-- Oracle 21c Database Initialization Script
ALTER SESSION SET CONTAINER = XEPDB1;

-- 계정 생성 및 권한 부여 (이미 존재할 경우 오류 무시)
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER UBIG IDENTIFIED BY UBIG';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
GRANT CONNECT, RESOURCE, DBA TO UBIG;

ALTER SESSION SET CURRENT_SCHEMA = UBIG;


--  파일이 생성됨 - 월요일-3월-23-2026   
--  DDL for Sequence SEQ_ACTIVITIES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ACTIVITIES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMIN_CHAT
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ADMIN_CHAT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADOPTION_APPS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ADOPTION_APPS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ADOPTION_POSTS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ADOPTION_POSTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ANIMAL_DETAILS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ANIMAL_DETAILS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARDS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BOARDS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_ATTACH
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BOARD_ATTACH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_LIKES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_BOARD_LIKES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CMT_ATTACH
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_CMT_ATTACH"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENTS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_COMMENTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENT_LIKES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_COMMENT_LIKES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DONATIONS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_DONATIONS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DONATION_FILES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_DONATION_FILES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FUNDINGS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FUNDINGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FUNDING_HIS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_FUNDING_HIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_KICKS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_KICKS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MESSAGES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_MESSAGES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SIGNS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_SIGNS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TAGS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_TAGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TAG_INFOS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_TAG_INFOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_VOL_COMMENTS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_VOL_COMMENTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_VOL_REVIEWS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_VOL_REVIEWS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACTIVITIES
--------------------------------------------------------

  CREATE TABLE "ACTIVITIES" 
   (    "ACT_ID" NUMBER, 
    "ADMIN_ID" VARCHAR2(30 BYTE), 
    "ACT_DATE" DATE, 
    "ACT_END" DATE, 
    "ACT_ADDRESS" VARCHAR2(255 BYTE), 
    "ACT_LAT" NUMBER(10,7), 
    "ACT_LON" NUMBER(10,7), 
    "ACT_LOAD" DATE, 
    "ACT_TITLE" VARCHAR2(50 BYTE), 
    "ACT_MAX" NUMBER, 
    "ACT_CUR" NUMBER, 
    "ACT_MONEY" NUMBER,
    "ACT_RATE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ACTIVITIES"."ACT_ID" IS '프로그램ID';
   COMMENT ON COLUMN "ACTIVITIES"."ADMIN_ID" IS '관리자ID';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_DATE" IS '시작일정';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_END" IS '종료일정';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_ADDRESS" IS '봉사활동주소';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_LAT" IS '위도';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_LON" IS '경도';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_LOAD" IS '게시일자';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_TITLE" IS '제목';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_MAX" IS '최대신청자수';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_CUR" IS '현재신청자수';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_MONEY" IS '후원금액';
   COMMENT ON COLUMN "ACTIVITIES"."ACT_RATE" IS '활동평점';
--------------------------------------------------------
--  DDL for Table ADMIN_CHAT_HISTORIES
--------------------------------------------------------

  CREATE TABLE "ADMIN_CHAT_HISTORIES" 
   (    "CHAT_NO" NUMBER, 
    "CHAT_SEND_USER_ID" VARCHAR2(30 BYTE), 
    "CHAT_RECEIVE_USER_ID" VARCHAR2(30 BYTE), 
    "CHAT_CONTENT" VARCHAR2(200 BYTE), 
    "CHAT_IS_CHECK" VARCHAR2(1 BYTE), 
    "CHAT_CREATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ADMIN_CHAT_HISTORIES"."CHAT_NO" IS '채팅번호';
   COMMENT ON COLUMN "ADMIN_CHAT_HISTORIES"."CHAT_SEND_USER_ID" IS '채팅수신인';
   COMMENT ON COLUMN "ADMIN_CHAT_HISTORIES"."CHAT_RECEIVE_USER_ID" IS '채팅발신인';
   COMMENT ON COLUMN "ADMIN_CHAT_HISTORIES"."CHAT_CONTENT" IS '채팅내용';
   COMMENT ON COLUMN "ADMIN_CHAT_HISTORIES"."CHAT_IS_CHECK" IS '채팅확인여부';
   COMMENT ON COLUMN "ADMIN_CHAT_HISTORIES"."CHAT_CREATE_DATE" IS '채팅발신일자';
--------------------------------------------------------
--  DDL for Table ADOPTION_APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "ADOPTION_APPLICATIONS" 
   (    "ADOPTION_APP_ID" NUMBER, 
    "ANIMAL_NO" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "ADOPT_STATUS" NUMBER, 
    "APPLY_DT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ADOPTION_APPLICATIONS"."ADOPTION_APP_ID" IS '신청번호';
   COMMENT ON COLUMN "ADOPTION_APPLICATIONS"."ANIMAL_NO" IS '동물 상세 고유 번호';
   COMMENT ON COLUMN "ADOPTION_APPLICATIONS"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "ADOPTION_APPLICATIONS"."ADOPT_STATUS" IS '신청상태';
   COMMENT ON COLUMN "ADOPTION_APPLICATIONS"."APPLY_DT" IS '신청날짜';
--------------------------------------------------------
--  DDL for Table ADOPTION_POSTS
--------------------------------------------------------

  CREATE TABLE "ADOPTION_POSTS" 
   (    "POST_NO" NUMBER, 
    "ANIMAL_NO" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "POST_TITLE" VARCHAR2(100 BYTE), 
    "POST_REG_DATE" DATE, 
    "POST_UPDATE_DATE" DATE, 
    "VIEWS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ADOPTION_POSTS"."POST_NO" IS '게시물 고유 번호';
   COMMENT ON COLUMN "ADOPTION_POSTS"."ANIMAL_NO" IS '동물 상세 고유 번호';
   COMMENT ON COLUMN "ADOPTION_POSTS"."USER_ID" IS '관리자아이디';
   COMMENT ON COLUMN "ADOPTION_POSTS"."POST_TITLE" IS '게시물 제목';
   COMMENT ON COLUMN "ADOPTION_POSTS"."POST_REG_DATE" IS '게시물 등록일';
   COMMENT ON COLUMN "ADOPTION_POSTS"."POST_UPDATE_DATE" IS '게시물 최종 수정일';
   COMMENT ON COLUMN "ADOPTION_POSTS"."VIEWS" IS '게시물 조회수';
--------------------------------------------------------
--  DDL for Table ANIMAL_DETAILS
--------------------------------------------------------

  CREATE TABLE "ANIMAL_DETAILS" 
   (    "ANIMAL_NO" NUMBER, 
    "SPECIES" NUMBER, 
    "ANIMAL_NAME" VARCHAR2(100 BYTE), 
    "BREED" VARCHAR2(100 BYTE), 
    "GENDER" NUMBER, 
    "AGE" NUMBER, 
    "WEIGHT" NUMBER, 
    "PET_SIZE" NUMBER, 
    "NEUTERED" NUMBER, 
    "VACCINATION_STATUS" VARCHAR2(1000 BYTE), 
    "HEALTH_NOTES" VARCHAR2(1000 BYTE), 
    "ADOPTION_STATUS" VARCHAR2(10 BYTE), 
    "ADOPTION_CONDITIONS" VARCHAR2(1000 BYTE), 
    "PHOTO_URL" VARCHAR2(1000 BYTE), 
    "HOPE_REGION" VARCHAR2(100 BYTE), 
    "DEADLINE_DATE" DATE, 
    "USER_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ANIMAL_DETAILS"."ANIMAL_NO" IS '동물 상세 고유 번호';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."SPECIES" IS '강아지/고양이 여부';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."ANIMAL_NAME" IS '동물의 이름';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."BREED" IS '품종';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."GENDER" IS '성별';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."AGE" IS '나이';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."WEIGHT" IS '체중';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."PET_SIZE" IS '크기';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."NEUTERED" IS '중성화여부';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."VACCINATION_STATUS" IS '접종 상태';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."HEALTH_NOTES" IS '특이사항';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."ADOPTION_STATUS" IS '입양 상태';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."ADOPTION_CONDITIONS" IS '입양 조건';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."PHOTO_URL" IS '동물사진/파일';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."HOPE_REGION" IS '입양 희망 지역';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."DEADLINE_DATE" IS '마감 기한';
   COMMENT ON COLUMN "ANIMAL_DETAILS"."USER_ID" IS '사용자 ID';
--------------------------------------------------------
--  DDL for Table BOARDS
--------------------------------------------------------

  CREATE TABLE "BOARDS" 
   (    "BOARD_ID" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "CATEGORY" VARCHAR2(50 BYTE), 
    "TITLE" VARCHAR2(100 BYTE), 
    "CONTENT" VARCHAR2(4000 BYTE), 
    "CREATE_DATE" DATE, 
    "UPDATE_DATE" DATE, 
    "VIEW_COUNT" NUMBER, 
    "IS_DELETED" CHAR(1 BYTE),
    "IS_PINNED" VARCHAR2(1 BYTE) DEFAULT 'N',
    "HASHTAGS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOARDS"."BOARD_ID" IS 'PK(게시글 고유번호)';
   COMMENT ON COLUMN "BOARDS"."USER_ID" IS 'FK(회원아이디)';
   COMMENT ON COLUMN "BOARDS"."CATEGORY" IS '게시글 유형(NOTICE,FREE,REQUEST,REVIEW)';
   COMMENT ON COLUMN "BOARDS"."TITLE" IS '제목';
   COMMENT ON COLUMN "BOARDS"."CONTENT" IS '내용';
   COMMENT ON COLUMN "BOARDS"."CREATE_DATE" IS '등록일시';
   COMMENT ON COLUMN "BOARDS"."UPDATE_DATE" IS '수정일시';
   COMMENT ON COLUMN "BOARDS"."VIEW_COUNT" IS '조회수';
   COMMENT ON COLUMN "BOARDS"."IS_DELETED" IS '삭제여부(Y/N)';
   COMMENT ON COLUMN "BOARDS"."IS_PINNED" IS '상단고정여부(Y/N)';
   COMMENT ON COLUMN "BOARDS"."HASHTAGS" IS '해시태그(콤마구분)';
--------------------------------------------------------
--  DDL for Table BOARD_ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "BOARD_ATTACHMENTS" 
   (    "FILE_ID" NUMBER, 
    "BOARD_ID" NUMBER, 
    "REF_TYPE" VARCHAR2(20 BYTE), 
    "REF_ID" VARCHAR2(20 BYTE), 
    "ORIGINAL_NAME" VARCHAR2(255 BYTE), 
    "SAVED_NAME" VARCHAR2(255 BYTE), 
    "FILE_PATH" VARCHAR2(255 BYTE), 
    "FILE_SIZE" NUMBER, 
    "CREATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."FILE_ID" IS 'PK(파일 고유번호)';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."BOARD_ID" IS 'PK(게시글 고유번호)';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."REF_TYPE" IS '연결대상 유형(BOARD,COMMENT)';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."REF_ID" IS '연결대상 ID(BOARD_ID / COMMENT_ID)';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."ORIGINAL_NAME" IS '사용자가 업로드한 파일명';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."SAVED_NAME" IS '서버에 저장된 고유 파일명';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."FILE_PATH" IS '파일저장경로';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."FILE_SIZE" IS '파일크기(BYTES)';
   COMMENT ON COLUMN "BOARD_ATTACHMENTS"."CREATE_DATE" IS '등록일시';
--------------------------------------------------------
--  DDL for Table BOARD_LIKES
--------------------------------------------------------

  CREATE TABLE "BOARD_LIKES" 
   (    "LIKE_ID" NUMBER, 
    "BOARD_ID" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "TARGET_TYPE" VARCHAR2(50 BYTE), 
    "CREATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BOARD_LIKES"."LIKE_ID" IS 'PK(좋아요 고유번호)';
   COMMENT ON COLUMN "BOARD_LIKES"."BOARD_ID" IS 'FK(게시판 고유번호)';
   COMMENT ON COLUMN "BOARD_LIKES"."USER_ID" IS 'FK(좋아요를 누른 사용자의 ID)';
   COMMENT ON COLUMN "BOARD_LIKES"."TARGET_TYPE" IS '대상유형(BOARD, COMMENT)';
   COMMENT ON COLUMN "BOARD_LIKES"."CREATE_DATE" IS '좋아요 등록일시';
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "COMMENTS" 
   (    "COMMENT_ID" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "BOARD_ID" NUMBER, 
    "CONTENT" VARCHAR2(1000 BYTE), 
    "CREATE_DATE" DATE, 
    "UPDATE_DATE" DATE, 
    "IS_DELETED" CHAR(1 BYTE), 
    "PARENT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "COMMENTS"."COMMENT_ID" IS 'PF(댓글 고유번호)';
   COMMENT ON COLUMN "COMMENTS"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "COMMENTS"."BOARD_ID" IS 'PK(게시판 고유번호)';
   COMMENT ON COLUMN "COMMENTS"."CONTENT" IS '댓글 내용';
   COMMENT ON COLUMN "COMMENTS"."CREATE_DATE" IS '등록일시';
   COMMENT ON COLUMN "COMMENTS"."UPDATE_DATE" IS '수정일시';
   COMMENT ON COLUMN "COMMENTS"."IS_DELETED" IS '삭제여부(Y/N)';
   COMMENT ON COLUMN "COMMENTS"."PARENT_ID" IS '부모댓글ID(대댓글)';
--------------------------------------------------------
--  DDL for Table COMMENT_ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "COMMENT_ATTACHMENTS" 
   (    "FILE_ID" NUMBER, 
    "COMMENT_ID" NUMBER, 
    "REF_TYPE" VARCHAR2(20 BYTE), 
    "REF_ID" VARCHAR2(20 BYTE), 
    "ORIGINAL_NAME" VARCHAR2(255 BYTE), 
    "SAVED_NAME" VARCHAR2(255 BYTE), 
    "FILE_PATH" VARCHAR2(255 BYTE), 
    "FILE_SIZE" NUMBER, 
    "CREATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."FILE_ID" IS 'PK(파일 고유번호)';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."COMMENT_ID" IS 'PF(댓글 고유번호)';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."REF_TYPE" IS '연결대상 유형(BOARD,COMMENT)';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."REF_ID" IS '연결대상 ID(BOARD_ID / COMMENT_ID)';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."ORIGINAL_NAME" IS '사용자가 업로드한 파일명';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."SAVED_NAME" IS '서버에 저장된 고유 파일명';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."FILE_PATH" IS '파일저장경로';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."FILE_SIZE" IS '파일크기(BYTES)';
   COMMENT ON COLUMN "COMMENT_ATTACHMENTS"."CREATE_DATE" IS '등록일시';
--------------------------------------------------------
--  DDL for Table COMMENT_LIKES
--------------------------------------------------------

  CREATE TABLE "COMMENT_LIKES" 
   (    "LIKE_ID" NUMBER, 
    "COMMENT_ID" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "TARGET_TYPE" VARCHAR2(50 BYTE), 
    "CREATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "COMMENT_LIKES"."LIKE_ID" IS 'PF(좋아요 고유번호)';
   COMMENT ON COLUMN "COMMENT_LIKES"."COMMENT_ID" IS 'PF(댓글 고유번호)';
   COMMENT ON COLUMN "COMMENT_LIKES"."USER_ID" IS 'FK(좋아요를 누른 사용자의 ID)';
   COMMENT ON COLUMN "COMMENT_LIKES"."TARGET_TYPE" IS '대상유형(BOARD, COMMENT)';
   COMMENT ON COLUMN "COMMENT_LIKES"."CREATE_DATE" IS '좋아요 등록일시';
--------------------------------------------------------
--  DDL for Table DONATIONS
--------------------------------------------------------

  CREATE TABLE "DONATIONS" 
   (    "DONATION_NO" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "DONATION_TYPE" NUMBER, 
    "DONATION_MONEY" NUMBER, 
    "DONATION_YN" NUMBER, 
    "DONATION_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DONATIONS"."DONATION_NO" IS '입금번호';
   COMMENT ON COLUMN "DONATIONS"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "DONATIONS"."DONATION_TYPE" IS '후원타입';
   COMMENT ON COLUMN "DONATIONS"."DONATION_MONEY" IS '후원금액';
   COMMENT ON COLUMN "DONATIONS"."DONATION_YN" IS '신청여부';
   COMMENT ON COLUMN "DONATIONS"."DONATION_DATE" IS '입금날짜';
--------------------------------------------------------
--  DDL for Table DONATION_FILES
--------------------------------------------------------

  CREATE TABLE "DONATION_FILES" 
   (    "FILE_ID" NUMBER, 
    "F_NO" NUMBER, 
    "ORIGINAL_NAME" VARCHAR2(255 BYTE), 
    "SAVED_NAME" VARCHAR2(255 BYTE), 
    "FILE_PATH" VARCHAR2(255 BYTE), 
    "FILE_SIZE" NUMBER, 
    "CREATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DONATION_FILES"."FILE_ID" IS 'PK(파일 고유번호)';
   COMMENT ON COLUMN "DONATION_FILES"."F_NO" IS '펀딩번호';
   COMMENT ON COLUMN "DONATION_FILES"."ORIGINAL_NAME" IS '사용자가 업로드한 파일명';
   COMMENT ON COLUMN "DONATION_FILES"."SAVED_NAME" IS '서버에 저장된 고유 파일명';
   COMMENT ON COLUMN "DONATION_FILES"."FILE_PATH" IS '파일저장경로';
   COMMENT ON COLUMN "DONATION_FILES"."FILE_SIZE" IS '파일크기(BYTES)';
   COMMENT ON COLUMN "DONATION_FILES"."CREATE_DATE" IS '등록일시';
--------------------------------------------------------
--  DDL for Table FUNDINGS
--------------------------------------------------------

  CREATE TABLE "FUNDINGS" 
   (    "F_NO" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "F_TITLE" VARCHAR2(30 BYTE), 
    "F_CONTENT" VARCHAR2(1000 BYTE), 
    "F_MAX_MONEY" NUMBER, 
    "F_CURRENT_MONEY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FUNDINGS"."F_NO" IS '펀딩번호';
   COMMENT ON COLUMN "FUNDINGS"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "FUNDINGS"."F_TITLE" IS '제목';
   COMMENT ON COLUMN "FUNDINGS"."F_CONTENT" IS '내용';
   COMMENT ON COLUMN "FUNDINGS"."F_MAX_MONEY" IS '목표금액';
   COMMENT ON COLUMN "FUNDINGS"."F_CURRENT_MONEY" IS '현재금액';
--------------------------------------------------------
--  DDL for Table FUNDING_HISTORIES
--------------------------------------------------------

  CREATE TABLE "FUNDING_HISTORIES" 
   (    "FH_NO" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "F_NO" NUMBER, 
    "F_MONEY" NUMBER, 
    "INPUT_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FUNDING_HISTORIES"."FH_NO" IS '입금번호';
   COMMENT ON COLUMN "FUNDING_HISTORIES"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "FUNDING_HISTORIES"."F_NO" IS '펀딩번호';
   COMMENT ON COLUMN "FUNDING_HISTORIES"."F_MONEY" IS '후원금액';
   COMMENT ON COLUMN "FUNDING_HISTORIES"."INPUT_DATE" IS '입금날짜';
--------------------------------------------------------
--  DDL for Table KICKS
--------------------------------------------------------

  CREATE TABLE "KICKS" 
   (    "KICK_NO" NUMBER, 
    "KICKER" VARCHAR2(30 BYTE), 
    "KICKED_USER" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KICKS"."KICK_NO" IS '차단번호';
   COMMENT ON COLUMN "KICKS"."KICKER" IS '차단한 사람';
   COMMENT ON COLUMN "KICKS"."KICKED_USER" IS '차단당한 사람';
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "MEMBERS" 
   (    "USER_ID" VARCHAR2(30 BYTE), 
    "USER_PWD" VARCHAR2(100 BYTE), 
    "USER_NAME" VARCHAR2(50 BYTE), 
    "USER_NICKNAME" VARCHAR2(30 BYTE), 
    "USER_ADDRESS" VARCHAR2(200 BYTE), 
    "USER_CONTACT" VARCHAR2(20 BYTE), 
    "USER_GENDER" VARCHAR2(1 BYTE), 
    "USER_AGE" NUMBER, 
    "USER_ATTENDED_COUNT" NUMBER, 
    "USER_RESTRICT_END_DATE" DATE, 
    "USER_STATUS" VARCHAR2(1 BYTE), 
    "USER_ROLE" VARCHAR2(10 BYTE), 
    "USER_ENROLL_DATE" DATE, 
    "USER_MODIFY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MEMBERS"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "MEMBERS"."USER_PWD" IS '회원비밀번호';
   COMMENT ON COLUMN "MEMBERS"."USER_NAME" IS '회원이름';
   COMMENT ON COLUMN "MEMBERS"."USER_NICKNAME" IS '회원닉네임';
   COMMENT ON COLUMN "MEMBERS"."USER_ADDRESS" IS '회원주소';
   COMMENT ON COLUMN "MEMBERS"."USER_CONTACT" IS '회원전화번호';
   COMMENT ON COLUMN "MEMBERS"."USER_GENDER" IS '회원성별';
   COMMENT ON COLUMN "MEMBERS"."USER_AGE" IS '회원나이';
   COMMENT ON COLUMN "MEMBERS"."USER_ATTENDED_COUNT" IS '봉사활동참가횟수';
   COMMENT ON COLUMN "MEMBERS"."USER_RESTRICT_END_DATE" IS '정지해제일자';
   COMMENT ON COLUMN "MEMBERS"."USER_STATUS" IS '회원가입여부';
   COMMENT ON COLUMN "MEMBERS"."USER_ROLE" IS '회원역할';
   COMMENT ON COLUMN "MEMBERS"."USER_ENROLL_DATE" IS '회원가입날짜';
   COMMENT ON COLUMN "MEMBERS"."USER_MODIFY_DATE" IS '회원정보수정날짜';
--------------------------------------------------------
--  DDL for Table MESSAGES
--------------------------------------------------------

  CREATE TABLE "MESSAGES" 
   (    "MESSAGE_NO" NUMBER, 
    "MESSAGE_SEND_USER_ID" VARCHAR2(30 BYTE), 
    "MESSAGE_RECEIVE_USER_ID" VARCHAR2(30 BYTE), 
    "MESSAGE_CONTENT" VARCHAR2(200 BYTE), 
    "MESSAGE_IS_CHECK" VARCHAR2(1 BYTE), 
    "MESSAGE_CREATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "MESSAGES"."MESSAGE_NO" IS '쪽지번호';
   COMMENT ON COLUMN "MESSAGES"."MESSAGE_SEND_USER_ID" IS '쪽지수신인';
   COMMENT ON COLUMN "MESSAGES"."MESSAGE_RECEIVE_USER_ID" IS '쪽지발신인';
   COMMENT ON COLUMN "MESSAGES"."MESSAGE_CONTENT" IS '쪽지내용';
   COMMENT ON COLUMN "MESSAGES"."MESSAGE_IS_CHECK" IS '쪽지확인여부';
   COMMENT ON COLUMN "MESSAGES"."MESSAGE_CREATE_DATE" IS '쪽지발신일자';
--------------------------------------------------------
--  DDL for Table SIGNS
--------------------------------------------------------

  CREATE TABLE "SIGNS" 
   (    "SIGNS_NO" NUMBER, 
    "ACT_ID" NUMBER, 
    "SIGNS_ID" VARCHAR2(30 BYTE), 
    "SIGNS_WAIT" NUMBER, 
    "SIGNS_STATUS" NUMBER, 
    "SIGNS_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SIGNS"."SIGNS_NO" IS '신청번호';
   COMMENT ON COLUMN "SIGNS"."ACT_ID" IS '프로그램ID';
   COMMENT ON COLUMN "SIGNS"."SIGNS_ID" IS '회원아이디';
   COMMENT ON COLUMN "SIGNS"."SIGNS_WAIT" IS '대기번호';
   COMMENT ON COLUMN "SIGNS"."SIGNS_STATUS" IS '신청상태';
   COMMENT ON COLUMN "SIGNS"."SIGNS_DATE" IS '신청날짜';
--------------------------------------------------------
--  DDL for Table TAGS
--------------------------------------------------------

  CREATE TABLE "TAGS" 
   (    "TAG_NO" NUMBER, 
    "ACT_ID" NUMBER, 
    "TAG_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TAGS"."TAG_NO" IS '태그등록정보번호';
   COMMENT ON COLUMN "TAGS"."ACT_ID" IS '프로그램ID';
   COMMENT ON COLUMN "TAGS"."TAG_ID" IS '태그ID';
--------------------------------------------------------
--  DDL for Table TAG_INFOS
--------------------------------------------------------

  CREATE TABLE "TAG_INFOS" 
   (    "TAG_ID" NUMBER, 
    "TAG_NAME" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TAG_INFOS"."TAG_ID" IS '태그ID';
   COMMENT ON COLUMN "TAG_INFOS"."TAG_NAME" IS '태그명';
--------------------------------------------------------
--  DDL for Table VOLUNTEER_BOARD_COMMENTS
--------------------------------------------------------

  CREATE TABLE "VOLUNTEER_BOARD_COMMENTS" 
   (    "CMT_NO" NUMBER, 
    "ACT_ID" NUMBER, 
    "USER_ID" VARCHAR2(30 BYTE), 
    "CMT_ANSWER" VARCHAR2(2000 BYTE), 
    "CMT_DATE" DATE, 
    "CMT_UPDATE" DATE, 
    "CMT_REMOVE" NUMBER,
    "CMT_RATE" NUMBER,
    "REVIEW_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."CMT_NO" IS '댓글번호';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."ACT_ID" IS '프로그램ID';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."USER_ID" IS '회원아이디';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."CMT_ANSWER" IS '봉사활동댓글';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."CMT_DATE" IS '작성일시';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."CMT_UPDATE" IS '수정';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."CMT_REMOVE" IS '삭제';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."CMT_RATE" IS '댓글평점';
   COMMENT ON COLUMN "VOLUNTEER_BOARD_COMMENTS"."REVIEW_NO" IS '후기번호(연결용)';
--------------------------------------------------------
--  DDL for Table VOLUNTEER_REVIEWS
--------------------------------------------------------

  CREATE TABLE "VOLUNTEER_REVIEWS" 
   (    "REVIEW_NO" NUMBER, 
    "ACT_ID" NUMBER, 
    "R_ID" VARCHAR2(30 BYTE), 
    "R_TITLE" VARCHAR2(200 BYTE),
    "R_REVIEW" VARCHAR2(4000 BYTE), 
    "R_RATE" NUMBER, 
    "R_CREATE" DATE, 
    "R_UPDATE" DATE, 
    "R_REMOVE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."REVIEW_NO" IS '후기번호';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."ACT_ID" IS '프로그램ID';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."R_ID" IS '회원아이디';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."R_TITLE" IS '후기제목';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."R_REVIEW" IS '봉사활동후기';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."R_RATE" IS '봉사평점';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."R_CREATE" IS '작성일시';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."R_UPDATE" IS '수정일시';
   COMMENT ON COLUMN "VOLUNTEER_REVIEWS"."R_REMOVE" IS '후기삭제';
REM INSERTING into ACTIVITIES
SET DEFINE OFF;
REM INSERTING into ADMIN_CHAT_HISTORIES
SET DEFINE OFF;
REM INSERTING into ADOPTION_APPLICATIONS
SET DEFINE OFF;
REM INSERTING into ADOPTION_POSTS
SET DEFINE OFF;
REM INSERTING into ANIMAL_DETAILS
SET DEFINE OFF;
Insert into ANIMAL_DETAILS (ANIMAL_NO,SPECIES,ANIMAL_NAME,BREED,GENDER,AGE,WEIGHT,PET_SIZE,NEUTERED,VACCINATION_STATUS,HEALTH_NOTES,ADOPTION_STATUS,ADOPTION_CONDITIONS,PHOTO_URL,HOPE_REGION,DEADLINE_DATE,USER_ID) values (1,2,'고양이','냥이',1,2.3,5.2,11,0,'11','22','대기중','33','2025122716522282993.JPG','인천 연수구 경원대로 294 14',to_date('25/12/26','RR/MM/DD'),'rlawlghks');
REM INSERTING into BOARDS
SET DEFINE OFF;
REM INSERTING into BOARD_ATTACHMENTS
SET DEFINE OFF;
REM INSERTING into BOARD_LIKES
SET DEFINE OFF;
REM INSERTING into COMMENTS
SET DEFINE OFF;
REM INSERTING into COMMENT_ATTACHMENTS
SET DEFINE OFF;
REM INSERTING into COMMENT_LIKES
SET DEFINE OFF;
REM INSERTING into DONATIONS
SET DEFINE OFF;
REM INSERTING into DONATION_FILES
SET DEFINE OFF;
REM INSERTING into FUNDINGS
SET DEFINE OFF;
REM INSERTING into FUNDING_HISTORIES
SET DEFINE OFF;
REM INSERTING into KICKS
SET DEFINE OFF;
REM INSERTING into MEMBERS
SET DEFINE OFF;
-- 테스트 계정 (admin/admin, user01/pass01, user02/pass02) - BCrypt 10 rounds
Insert into MEMBERS (USER_ID,USER_PWD,USER_NAME,USER_NICKNAME,USER_ADDRESS,USER_CONTACT,USER_GENDER,USER_AGE,USER_ATTENDED_COUNT,USER_RESTRICT_END_DATE,USER_STATUS,USER_ROLE,USER_ENROLL_DATE,USER_MODIFY_DATE) values ('admin','$2a$10$HrVlNcwE/Z6JGK5Caiww..LQYJCtXBDMlcTw84M2wYyCV8bza7qke','관리자','어드민','서울시 강남구','010-0000-0000','M',30,0,to_date('00/01/01','RR/MM/DD'),'Y','ADMIN',SYSDATE,SYSDATE);
Insert into MEMBERS (USER_ID,USER_PWD,USER_NAME,USER_NICKNAME,USER_ADDRESS,USER_CONTACT,USER_GENDER,USER_AGE,USER_ATTENDED_COUNT,USER_RESTRICT_END_DATE,USER_STATUS,USER_ROLE,USER_ENROLL_DATE,USER_MODIFY_DATE) values ('user01','$2a$10$.gU0UeKyES42t8/n8bDa.Ox0GA9vSAGDSNSzZ6Y7k4z0cKGy7QoIO','테스트유저01','유저01','서울시 마포구','010-1111-1111','M',25,0,to_date('00/01/01','RR/MM/DD'),'Y','USER',SYSDATE,SYSDATE);
Insert into MEMBERS (USER_ID,USER_PWD,USER_NAME,USER_NICKNAME,USER_ADDRESS,USER_CONTACT,USER_GENDER,USER_AGE,USER_ATTENDED_COUNT,USER_RESTRICT_END_DATE,USER_STATUS,USER_ROLE,USER_ENROLL_DATE,USER_MODIFY_DATE) values ('user02','$2a$10$mbhImpthWJ/1ipDqhLHox.wo8vGs3HhRbh9pVghAefqv1yWlePEbi','테스트유저02','유저02','서울시 서초구','010-2222-2222','F',23,0,to_date('00/01/01','RR/MM/DD'),'Y','USER',SYSDATE,SYSDATE);
REM INSERTING into MESSAGES
SET DEFINE OFF;
REM INSERTING into SIGNS
SET DEFINE OFF;
REM INSERTING into TAGS
SET DEFINE OFF;
REM INSERTING into TAG_INFOS
SET DEFINE OFF;
REM INSERTING into VOLUNTEER_BOARD_COMMENTS
SET DEFINE OFF;
REM INSERTING into VOLUNTEER_REVIEWS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ACTIVITIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ACTIVITIES" ON "ACTIVITIES" ("ACT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ADMIN_CHAT_HISTORIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ADMIN_CHAT_HISTORIES" ON "ADMIN_CHAT_HISTORIES" ("CHAT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ADOPTION_APPLICATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ADOPTION_APPLICATIONS" ON "ADOPTION_APPLICATIONS" ("ADOPTION_APP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ADOPTION_POSTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ADOPTION_POSTS" ON "ADOPTION_POSTS" ("POST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ANIMAL_DETAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ANIMAL_DETAILS" ON "ANIMAL_DETAILS" ("ANIMAL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BOARDS" ON "BOARDS" ("BOARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_ATTACHMENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BOARD_ATTACHMENTS" ON "BOARD_ATTACHMENTS" ("FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOARD_LIKES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_BOARD_LIKES" ON "BOARD_LIKES" ("LIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_COMMENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_COMMENTS" ON "COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_COMMENT_ATTACHMENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_COMMENT_ATTACHMENTS" ON "COMMENT_ATTACHMENTS" ("FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_COMMENT_LIKES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_COMMENT_LIKES" ON "COMMENT_LIKES" ("LIKE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DONATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DONATIONS" ON "DONATIONS" ("DONATION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DONATION_FILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DONATION_FILES" ON "DONATION_FILES" ("FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FUNDINGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FUNDINGS" ON "FUNDINGS" ("F_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FUNDING_HISTORIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FUNDING_HISTORIES" ON "FUNDING_HISTORIES" ("FH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_KICKS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_KICKS" ON "KICKS" ("KICK_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MEMBERS" ON "MEMBERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MESSAGES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MESSAGES" ON "MESSAGES" ("MESSAGE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SIGNS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SIGNS" ON "SIGNS" ("SIGNS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TAGS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TAGS" ON "TAGS" ("TAG_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TAG_INFOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TAG_INFOS" ON "TAG_INFOS" ("TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_VOLUNTEER_BOARD_COMMENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VOLUNTEER_BOARD_COMMENTS" ON "VOLUNTEER_BOARD_COMMENTS" ("CMT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_VOLUNTEER_REVIEWS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VOLUNTEER_REVIEWS" ON "VOLUNTEER_REVIEWS" ("REVIEW_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADOPTION_POSTS
--------------------------------------------------------

  ALTER TABLE "ADOPTION_POSTS" MODIFY ("POST_NO" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_POSTS" MODIFY ("ANIMAL_NO" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_POSTS" ADD CONSTRAINT "PK_ADOPTION_POSTS" PRIMARY KEY ("POST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADOPTION_POSTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_POSTS" MODIFY ("POST_TITLE" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_POSTS" MODIFY ("POST_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_POSTS" MODIFY ("POST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_POSTS" MODIFY ("VIEWS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("REF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("REF_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("ORIGINAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("SAVED_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOARD_ATTACHMENTS" ADD CONSTRAINT "PK_BOARD_ATTACHMENTS" PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOLUNTEER_REVIEWS
--------------------------------------------------------

  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("REVIEW_NO" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("ACT_ID" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("R_ID" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("R_REVIEW" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("R_RATE" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("R_CREATE" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("R_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" MODIFY ("R_REMOVE" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_REVIEWS" ADD CONSTRAINT "PK_VOLUNTEER_REVIEWS" PRIMARY KEY ("REVIEW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" ADD CONSTRAINT "PK_COMMENTS" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "COMMENTS" MODIFY ("IS_DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DONATION_FILES
--------------------------------------------------------

  ALTER TABLE "DONATION_FILES" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "DONATION_FILES" ADD CONSTRAINT "PK_DONATION_FILES" PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DONATION_FILES" MODIFY ("F_NO" NOT NULL ENABLE);
  ALTER TABLE "DONATION_FILES" MODIFY ("ORIGINAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "DONATION_FILES" MODIFY ("SAVED_NAME" NOT NULL ENABLE);
  ALTER TABLE "DONATION_FILES" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "DONATION_FILES" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "DONATION_FILES" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANIMAL_DETAILS
--------------------------------------------------------

  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("ANIMAL_NO" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("SPECIES" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("ANIMAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("BREED" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("WEIGHT" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("PET_SIZE" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("NEUTERED" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("VACCINATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("HEALTH_NOTES" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("ADOPTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("ADOPTION_CONDITIONS" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("PHOTO_URL" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("HOPE_REGION" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("DEADLINE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ANIMAL_DETAILS" ADD CONSTRAINT "PK_ANIMAL_DETAILS" PRIMARY KEY ("ANIMAL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANIMAL_DETAILS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENT_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "COMMENT_ATTACHMENTS" ADD CONSTRAINT "PK_COMMENT_ATTACHMENTS" PRIMARY KEY ("FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("REF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("REF_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("ORIGINAL_NAME" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("SAVED_NAME" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_ATTACHMENTS" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SIGNS
--------------------------------------------------------

  ALTER TABLE "SIGNS" MODIFY ("SIGNS_NO" NOT NULL ENABLE);
  ALTER TABLE "SIGNS" MODIFY ("ACT_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGNS" ADD CONSTRAINT "PK_SIGNS" PRIMARY KEY ("SIGNS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIGNS" MODIFY ("SIGNS_ID" NOT NULL ENABLE);
  ALTER TABLE "SIGNS" MODIFY ("SIGNS_WAIT" NOT NULL ENABLE);
  ALTER TABLE "SIGNS" MODIFY ("SIGNS_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SIGNS" MODIFY ("SIGNS_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FUNDING_HISTORIES
--------------------------------------------------------

  ALTER TABLE "FUNDING_HISTORIES" MODIFY ("FH_NO" NOT NULL ENABLE);
  ALTER TABLE "FUNDING_HISTORIES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDING_HISTORIES" MODIFY ("F_NO" NOT NULL ENABLE);
  ALTER TABLE "FUNDING_HISTORIES" MODIFY ("F_MONEY" NOT NULL ENABLE);
  ALTER TABLE "FUNDING_HISTORIES" MODIFY ("INPUT_DATE" NOT NULL ENABLE);
  ALTER TABLE "FUNDING_HISTORIES" ADD CONSTRAINT "PK_FUNDING_HISTORIES" PRIMARY KEY ("FH_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "MEMBERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_GENDER" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_AGE" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_ATTENDED_COUNT" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_RESTRICT_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_ENROLL_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" MODIFY ("USER_MODIFY_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBERS" ADD CONSTRAINT "PK_MEMBERS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "MESSAGES" MODIFY ("MESSAGE_NO" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("MESSAGE_SEND_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("MESSAGE_RECEIVE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("MESSAGE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("MESSAGE_IS_CHECK" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" MODIFY ("MESSAGE_CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "MESSAGES" ADD CONSTRAINT "PK_MESSAGES" PRIMARY KEY ("MESSAGE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACTIVITIES
--------------------------------------------------------

  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_ID" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_DATE" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_END" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_LAT" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_LON" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_LOAD" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_TITLE" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_MAX" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_CUR" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" MODIFY ("ACT_MONEY" NOT NULL ENABLE);
  ALTER TABLE "ACTIVITIES" ADD CONSTRAINT "PK_ACTIVITIES" PRIMARY KEY ("ACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADOPTION_APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "ADOPTION_APPLICATIONS" MODIFY ("ADOPTION_APP_ID" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_APPLICATIONS" MODIFY ("ANIMAL_NO" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_APPLICATIONS" ADD CONSTRAINT "PK_ADOPTION_APPLICATIONS" PRIMARY KEY ("ADOPTION_APP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADOPTION_APPLICATIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_APPLICATIONS" MODIFY ("ADOPT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADOPTION_APPLICATIONS" MODIFY ("APPLY_DT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENT_LIKES
--------------------------------------------------------

  ALTER TABLE "COMMENT_LIKES" MODIFY ("LIKE_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_LIKES" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_LIKES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_LIKES" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_LIKES" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "COMMENT_LIKES" ADD CONSTRAINT "PK_COMMENT_LIKES" PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNDINGS
--------------------------------------------------------

  ALTER TABLE "FUNDINGS" MODIFY ("F_NO" NOT NULL ENABLE);
  ALTER TABLE "FUNDINGS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "FUNDINGS" MODIFY ("F_TITLE" NOT NULL ENABLE);
  ALTER TABLE "FUNDINGS" MODIFY ("F_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "FUNDINGS" MODIFY ("F_MAX_MONEY" NOT NULL ENABLE);
  ALTER TABLE "FUNDINGS" MODIFY ("F_CURRENT_MONEY" NOT NULL ENABLE);
  ALTER TABLE "FUNDINGS" ADD CONSTRAINT "PK_FUNDINGS" PRIMARY KEY ("F_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KICKS
--------------------------------------------------------

  ALTER TABLE "KICKS" MODIFY ("KICK_NO" NOT NULL ENABLE);
  ALTER TABLE "KICKS" MODIFY ("KICKER" NOT NULL ENABLE);
  ALTER TABLE "KICKS" MODIFY ("KICKED_USER" NOT NULL ENABLE);
  ALTER TABLE "KICKS" ADD CONSTRAINT "PK_KICKS" PRIMARY KEY ("KICK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARDS
--------------------------------------------------------

  ALTER TABLE "BOARDS" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("VIEW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "BOARDS" ADD CONSTRAINT "PK_BOARDS" PRIMARY KEY ("BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN_CHAT_HISTORIES
--------------------------------------------------------

  ALTER TABLE "ADMIN_CHAT_HISTORIES" ADD CONSTRAINT "PK_ADMIN_CHAT_HISTORIES" PRIMARY KEY ("CHAT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN_CHAT_HISTORIES" MODIFY ("CHAT_NO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_CHAT_HISTORIES" MODIFY ("CHAT_SEND_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_CHAT_HISTORIES" MODIFY ("CHAT_RECEIVE_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_CHAT_HISTORIES" MODIFY ("CHAT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_CHAT_HISTORIES" MODIFY ("CHAT_IS_CHECK" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_CHAT_HISTORIES" MODIFY ("CHAT_CREATE_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_LIKES
--------------------------------------------------------

  ALTER TABLE "BOARD_LIKES" MODIFY ("LIKE_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARD_LIKES" ADD CONSTRAINT "PK_BOARD_LIKES" PRIMARY KEY ("LIKE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BOARD_LIKES" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARD_LIKES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOARD_LIKES" MODIFY ("TARGET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BOARD_LIKES" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOLUNTEER_BOARD_COMMENTS
--------------------------------------------------------

  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" MODIFY ("CMT_NO" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" MODIFY ("ACT_ID" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" ADD CONSTRAINT "PK_VOLUNTEER_BOARD_COMMENTS" PRIMARY KEY ("CMT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" MODIFY ("CMT_ANSWER" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" MODIFY ("CMT_DATE" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" MODIFY ("CMT_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" MODIFY ("CMT_REMOVE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DONATIONS
--------------------------------------------------------

  ALTER TABLE "DONATIONS" MODIFY ("DONATION_NO" NOT NULL ENABLE);
  ALTER TABLE "DONATIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DONATIONS" MODIFY ("DONATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DONATIONS" MODIFY ("DONATION_MONEY" NOT NULL ENABLE);
  ALTER TABLE "DONATIONS" MODIFY ("DONATION_YN" NOT NULL ENABLE);
  ALTER TABLE "DONATIONS" MODIFY ("DONATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "DONATIONS" ADD CONSTRAINT "PK_DONATIONS" PRIMARY KEY ("DONATION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAG_INFOS
--------------------------------------------------------

  ALTER TABLE "TAG_INFOS" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "TAG_INFOS" MODIFY ("TAG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TAG_INFOS" ADD CONSTRAINT "PK_TAG_INFOS" PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAGS
--------------------------------------------------------

  ALTER TABLE "TAGS" MODIFY ("TAG_NO" NOT NULL ENABLE);
  ALTER TABLE "TAGS" MODIFY ("ACT_ID" NOT NULL ENABLE);
  ALTER TABLE "TAGS" MODIFY ("TAG_ID" NOT NULL ENABLE);
  ALTER TABLE "TAGS" ADD CONSTRAINT "PK_TAGS" PRIMARY KEY ("TAG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACTIVITIES
--------------------------------------------------------

  ALTER TABLE "ACTIVITIES" ADD CONSTRAINT "FK_MEMBERS_TO_ACTIVITIES_1" FOREIGN KEY ("ADMIN_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADOPTION_APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "ADOPTION_APPLICATIONS" ADD CONSTRAINT "FK_ANIMAL_DETAILS_TO_ADOPTION_APPLICATIONS_1" FOREIGN KEY ("ANIMAL_NO")
      REFERENCES "ANIMAL_DETAILS" ("ANIMAL_NO") ENABLE;
  ALTER TABLE "ADOPTION_APPLICATIONS" ADD CONSTRAINT "FK_MEMBERS_TO_ADOPTION_APPLICATIONS_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADOPTION_POSTS
--------------------------------------------------------

  ALTER TABLE "ADOPTION_POSTS" ADD CONSTRAINT "FK_ANIMAL_DETAILS_TO_ADOPTION_POSTS_1" FOREIGN KEY ("ANIMAL_NO")
      REFERENCES "ANIMAL_DETAILS" ("ANIMAL_NO") ENABLE;
  ALTER TABLE "ADOPTION_POSTS" ADD CONSTRAINT "FK_MEMBERS_TO_ADOPTION_POSTS_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARDS
--------------------------------------------------------

  ALTER TABLE "BOARDS" ADD CONSTRAINT "FK_MEMBERS_TO_BOARDS_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "BOARD_ATTACHMENTS" ADD CONSTRAINT "FK_BOARDS_TO_BOARD_ATTACHMENTS_1" FOREIGN KEY ("BOARD_ID")
      REFERENCES "BOARDS" ("BOARD_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_LIKES
--------------------------------------------------------

  ALTER TABLE "BOARD_LIKES" ADD CONSTRAINT "FK_BOARDS_TO_BOARD_LIKES_1" FOREIGN KEY ("BOARD_ID")
      REFERENCES "BOARDS" ("BOARD_ID") ENABLE;
  ALTER TABLE "BOARD_LIKES" ADD CONSTRAINT "FK_MEMBERS_TO_BOARD_LIKES_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_MEMBERS_TO_COMMENTS_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
  ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_BOARDS_TO_COMMENTS_1" FOREIGN KEY ("BOARD_ID")
      REFERENCES "BOARDS" ("BOARD_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENT_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "COMMENT_ATTACHMENTS" ADD CONSTRAINT "FK_COMMENTS_TO_COMMENT_ATTACHMENTS_1" FOREIGN KEY ("COMMENT_ID")
      REFERENCES "COMMENTS" ("COMMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENT_LIKES
--------------------------------------------------------

  ALTER TABLE "COMMENT_LIKES" ADD CONSTRAINT "FK_COMMENTS_TO_COMMENT_LIKES_1" FOREIGN KEY ("COMMENT_ID")
      REFERENCES "COMMENTS" ("COMMENT_ID") ENABLE;
  ALTER TABLE "COMMENT_LIKES" ADD CONSTRAINT "FK_MEMBERS_TO_COMMENT_LIKES_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DONATIONS
--------------------------------------------------------

  ALTER TABLE "DONATIONS" ADD CONSTRAINT "FK_MEMBERS_TO_DONATIONS_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DONATION_FILES
--------------------------------------------------------

  ALTER TABLE "DONATION_FILES" ADD CONSTRAINT "FK_FUNDINGS_TO_DONATION_FILES_1" FOREIGN KEY ("F_NO")
      REFERENCES "FUNDINGS" ("F_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FUNDINGS
--------------------------------------------------------

  ALTER TABLE "FUNDINGS" ADD CONSTRAINT "FK_MEMBERS_TO_FUNDINGS_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FUNDING_HISTORIES
--------------------------------------------------------

  ALTER TABLE "FUNDING_HISTORIES" ADD CONSTRAINT "FK_MEMBERS_TO_FUNDING_HISTORIES_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
  ALTER TABLE "FUNDING_HISTORIES" ADD CONSTRAINT "FK_FUNDINGS_TO_FUNDING_HISTORIES_1" FOREIGN KEY ("F_NO")
      REFERENCES "FUNDINGS" ("F_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIGNS
--------------------------------------------------------

  ALTER TABLE "SIGNS" ADD CONSTRAINT "FK_ACTIVITIES_TO_SIGNS_1" FOREIGN KEY ("ACT_ID")
      REFERENCES "ACTIVITIES" ("ACT_ID") ENABLE;
  ALTER TABLE "SIGNS" ADD CONSTRAINT "FK_MEMBERS_TO_SIGNS_1" FOREIGN KEY ("SIGNS_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAGS
--------------------------------------------------------

  ALTER TABLE "TAGS" ADD CONSTRAINT "FK_ACTIVITIES_TO_TAGS_1" FOREIGN KEY ("ACT_ID")
      REFERENCES "ACTIVITIES" ("ACT_ID") ENABLE;
  ALTER TABLE "TAGS" ADD CONSTRAINT "FK_TAG_INFOS_TO_TAGS_1" FOREIGN KEY ("TAG_ID")
      REFERENCES "TAG_INFOS" ("TAG_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOLUNTEER_BOARD_COMMENTS
--------------------------------------------------------

  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" ADD CONSTRAINT "FK_ACTIVITIES_TO_VOLUNTEER_BOARD_COMMENTS_1" FOREIGN KEY ("ACT_ID")
      REFERENCES "ACTIVITIES" ("ACT_ID") ENABLE;
  ALTER TABLE "VOLUNTEER_BOARD_COMMENTS" ADD CONSTRAINT "FK_MEMBERS_TO_VOLUNTEER_BOARD_COMMENTS_1" FOREIGN KEY ("USER_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOLUNTEER_REVIEWS
--------------------------------------------------------

  ALTER TABLE "VOLUNTEER_REVIEWS" ADD CONSTRAINT "FK_ACTIVITIES_TO_VOLUNTEER_REVIEWS_1" FOREIGN KEY ("ACT_ID")
      REFERENCES "ACTIVITIES" ("ACT_ID") ENABLE;
  ALTER TABLE "VOLUNTEER_REVIEWS" ADD CONSTRAINT "FK_MEMBERS_TO_VOLUNTEER_REVIEWS_1" FOREIGN KEY ("R_ID")
      REFERENCES "MEMBERS" ("USER_ID") ENABLE;